### ISSUE TITLE
自動關閉

### ISSUE THREAD

**Issue by Weaponhaha** [dimotsai/kekeke-cq-bot#1]
每當bot回復一次就會自重shut down bot，請問這是什麼問題？

**Comment by dimotsai** [comment]
@Weaponhaha 有log嗎?

**Comment by Weaponhaha** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'bot' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'prebot', 'bot', 'postbot' ]
5 info lifecycle kekeke-cq-bot@1.1.0~prebot: kekeke-cq-bot@1.1.0
6 info lifecycle kekeke-cq-bot@1.1.0~bot: kekeke-cq-bot@1.1.0
7 verbose lifecycle kekeke-cq-bot@1.1.0~bot: unsafe-perm in lifecycle true
8 verbose lifecycle kekeke-cq-bot@1.1.0~bot: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\User\Desktop\Bot Test\kekeke-cq-bot\node_modules\.bin;C:\Users\User\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Skype\Phone\;C:\adb;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Users\User\AppData\Roaming\npm
9 verbose lifecycle kekeke-cq-bot@1.1.0~bot: CWD: C:\Users\User\Desktop\Bot Test\kekeke-cq-bot
10 silly lifecycle kekeke-cq-bot@1.1.0~bot: Args: [ '/d /s /c', 'node src/bot.js' ]
11 silly lifecycle kekeke-cq-bot@1.1.0~bot: Returned: code: 1  signal: null
12 info lifecycle kekeke-cq-bot@1.1.0~bot: Failed to exec bot script
13 verbose stack Error: kekeke-cq-bot@1.1.0 bot: `node src/bot.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid kekeke-cq-bot@1.1.0
15 verbose cwd C:\Users\User\Desktop\Bot Test\kekeke-cq-bot
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "bot"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error kekeke-cq-bot@1.1.0 bot: `node src/bot.js`
22 error Exit status 1
23 error Failed at the kekeke-cq-bot@1.1.0 bot script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]


這是最後一次運行自動關閉的Log.

**Comment by Weaponhaha** [comment]
這是最後一個運行后自動關閉的 Log.
由於太長了我放在GoogleDocs

https://docs.google.com/document/d/1f5TehNHIMbPkcoZDvHHBno0Da4pURFSd7UPieUGYhr4/edit?usp=sharing

**Comment by dimotsai** [comment]
@Weaponhaha 應該是 Kerma 不夠?
建議用pm2啟動bot，就算程式掛掉應該也會自動重啟

**Comment by Weaponhaha** [comment]
@dimotsai 但是我的Topic里沒有kerma限制，我試試用pm2吧。 想再問因為我的Topic有兩個Text Area,一個Post Link一個聊天，Bot在Link那邊說話，要去哪裡改？我看了各種Code，找不到哪裡改。

https://kekeke.cc/%E9%9B%AA%E5%A7%91%E6%A9%9F%E5%8F%8B  <-- Topic
